version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    env_file: .env
    container_name: foodgram_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lapindev/foodgram_backend
    volumes:
      - static_value:/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    container_name: foodgram_backend

  frontend:
    image: lapindev/foodgram_frontend
    container_name: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/frontend_static
    depends_on:
      - backend


  gateway:
    image: lapindev/foodgram_infra
    container_name: foodgram_infra
    env_file: .env
    volumes:
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - backend
    ports:
      - 8000:80

volumes:
  pg_data:
  static_value:
  media_value: