version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: lapindev/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    container_name: foodgram_backend

  frontend:
    image: lapindev/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend


  gateway:
    image: lapindev/foodgram_nginx
    container_name: foodgram_nginx
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - backend
    ports:
      - 8000:80

volumes:
  postgres_data:
  static_value:
  media_value: